### ISSUE TITLE
Implement more ways to convert files

### ISSUE THREAD

**Issue by ivbeg** [datacoon/undatum#1]
Add more file conversion types, like:
- jsonl to bson
- bson to jsonl
- xls to bson
- xlsx to bson
and e.t.c.

**Comment by tkerby** [comment]
I'd really like to see reverse conversions here like jsonl to csv. Given you have header detection already this should be relatively easy

**Comment by ivbeg** [comment]
@tkerby yes, it's quite simple, except cases when jsonl is not flat, but complex object. I've been thinking about that last days and wrote new issue right now #5

**Comment by ivbeg** [comment]
@tkerby added conversion of flat JSON lines to CSV, it's in release 1.0.7 and current code

**Comment by ivbeg** [comment]
All conversions added. Last one xlsx2bson will be in next release
